In [1]:
from pathlib import Path
import warnings

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.cluster import KMeans
from sklearn.mixture import GaussianMixture
from sklearn.metrics import silhouette_score
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE

warnings.filterwarnings("ignore", category=FutureWarning)
sns.set_theme(style="whitegrid", context="notebook")
RANDOM_STATE = 42
print("Libraries loaded successfully.")

Libraries loaded successfully.

In [2]:
#excel file path
DATA_PATH = Path(r"C:\Users\kacie\OneDrive - University of Bristol\FoAI\Coursework\data cleaning\MedHealth_SYNTHEA_GroupCW_Dataset_Final.csv")

if not DATA_PATH.exists():
    raise FileNotFoundError(
        f"Could not find {DATA_PATH}. Put the CSV file in the same folder as this notebook."
    )
        
raw = pd.read_csv(DATA_PATH)

print(f"Loaded {raw.shape[0]} rows and {raw.shape[1]} columns")
raw.head() #first 5 rows of data in the given excel file

raw.dtypes.value_counts() #count number of columns that have each data types

display(pd.DataFrame({
    "dtype": raw.dtypes.astype(str),
    "missing_n": raw.isna().sum(),
    "missing_percent": (100 * raw.isna().mean()).round(1),
    "unique_values": raw.nunique(dropna=True)
}).sort_values("missing_percent", ascending=False))

print("Exact duplicate rows:", raw.duplicated().sum())
display(raw.describe(include="all").T)

df = raw.copy()
date_cols = []
for c in df.columns:
    if c.endswith('_DATE') or c.startswith('PERIOD_'):
        date_cols.append(c)

print(date_cols)
display(raw[['BIRTH_DATE','PERIOD_START','PERIOD_END']].head())

for c in date_cols:
    df[c] = pd.to_datetime(df[c], format = '%d/%m/%Y') # tell panda that dates are in D/M/Y format, and change to Y/M/D format with .to_datetime
    
    
    
lost = {}
for c in date_cols:
    blanks_after = df[c].isna().sum()
    blanks_before = raw[c].isna().sum()
    blanks = blanks_after - blanks_before
    lost[c] = int(blanks)
print(lost) #to know any dates that cant be converted into Y/M/D format -> stayed (NaT) blanked

df[['BIRTH_DATE','PERIOD_START','PERIOD_END']].head()

Loaded 297 rows and 52 columns

,dtype,missing_n,missing_percent,unique_values
GLUCOSE_LAST_RECORDED,float64,176,59.3,107
GLUCOSE_DATE,str,176,59.3,101
CREATININE_LAST_RECORDED,float64,176,59.3,83
CREATININE_DATE,str,176,59.3,101
TRIGLYCERIDES_LAST_RECORDED,float64,128,43.1,96
TRIGLYCERIDES_DATE,str,128,43.1,97
HDL_CHOLESTEROL_DATE,str,128,43.1,97
HDL_CHOLESTEROL_LAST_RECORDED,float64,128,43.1,99
TOTAL_CHOLESTEROL_DATE,str,128,43.1,97
TOTAL_CHOLESTEROL_LAST_RECORDED,float64,128,43.1,99
WEIGHT_KG_LAST_IN_YEAR,float64,55,18.5,170
WEIGHT_KG_DATE,str,55,18.5,213
HEIGHT_CM_DATE,str,55,18.5,213
HEIGHT_CM_LAST_IN_YEAR,float64,55,18.5,131
PAIN_SCORE_DATE,str,54,18.2,214
PAIN_SCORE_LAST_IN_YEAR,float64,54,18.2,8
PATIENT_ID,str,0,0.0,100
BIRTH_DATE,str,0,0.0,96
SEX,str,0,0.0,2
RACE,str,0,0.0,3
ENCOUNTER_OTHER_RECORDS,int64,0,0.0,10
ENCOUNTER_INPATIENT_RECORDS,int64,0,0.0,5
ENCOUNTER_FOLLOW_UP_RECORDS,int64,0,0.0,6
ENCOUNTER_POSTNATAL_RECORDS,int64,0,0.0,2
ENCOUNTER_PRENATAL_RECORDS,int64,0,0.0,11
ENCOUNTER_WELL_CHILD_RECORDS,int64,0,0.0,7
ENCOUNTER_URGENT_CARE_RECORDS,int64,0,0.0,8
ENCOUNTER_EMERGENCY_ROOM_RECORDS,int64,0,0.0,3
ENCOUNTER_PROBLEM_RECORDS,int64,0,0.0,11
ENCOUNTER_GENERAL_EXAM_RECORDS,int64,0,0.0,2
ENCOUNTER_CHECK_UP_RECORDS,int64,0,0.0,12
ENCOUNTER_SYMPTOM_RECORDS,int64,0,0.0,5
RECORD_CUTOFF_DATE,str,0,0.0,10
PERIOD_END,str,0,0.0,4
PERIOD_START,str,0,0.0,6
YEAR,int64,0,0.0,3
SCREENING_ASSESSMENT_RECORDS,int64,0,0.0,25
DENTAL_PROCEDURE_RECORDS,int64,0,0.0,21
PROCEDURE_RECORDS,int64,0,0.0,62
MEDICATION_START_RECORDS,int64,0,0.0,20
OBESITY_HISTORY,int64,0,0.0,2
PREDIABETES_HISTORY,int64,0,0.0,2
HYPERTENSION_HISTORY,int64,0,0.0,2
ISCHEMIC_HEART_DISEASE_HISTORY,int64,0,0.0,2
HYPERLIPIDEMIA_HISTORY,int64,0,0.0,2
CHRONIC_PAIN_HISTORY,int64,0,0.0,2
ASTHMA_HISTORY,int64,0,0.0,2
CHRONIC_KIDNEY_DISEASE_HISTORY,int64,0,0.0,2
STRESS_HISTORY,int64,0,0.0,2
SOCIAL_ISOLATION_HISTORY,int64,0,0.0,2
UNEMPLOYMENT_HISTORY,int64,0,0.0,2
HOUSING_UNSATISFACTORY_HISTORY,int64,0,0.0,2

Exact duplicate rows: 0

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
PATIENT_ID,297,100,00bcbfc6-c7b9-bd0e-3d95-071f9fba6321,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
BIRTH_DATE,297,96,06/11/1979,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SEX,297,2,M,150,NaN,NaN,NaN,NaN,NaN,NaN,NaN
RACE,297,3,white,242,NaN,NaN,NaN,NaN,NaN,NaN,NaN
YEAR,297.0,NaN,NaN,NaN,2024.0,0.817875,2023.0,2023.0,2024.0,2025.0,2025.0
PERIOD_START,297,6,01/01/2025,99,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PERIOD_END,297,4,31/12/2024,99,NaN,NaN,NaN,NaN,NaN,NaN,NaN
RECORD_CUTOFF_DATE,297,10,23/08/2026,81,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ENCOUNTER_SYMPTOM_RECORDS,297.0,NaN,NaN,NaN,0.296296,0.636518,0.0,0.0,0.0,0.0,5.0
ENCOUNTER_CHECK_UP_RECORDS,297.0,NaN,NaN,NaN,0.804714,1.795898,0.0,0.0,0.0,1.0,15.0
ENCOUNTER_GENERAL_EXAM_RECORDS,297.0,NaN,NaN,NaN,0.572391,0.495567,0.0,0.0,1.0,1.0,1.0
ENCOUNTER_PROBLEM_RECORDS,297.0,NaN,NaN,NaN,1.37037,9.314922,0.0,0.0,0.0,0.0,87.0
ENCOUNTER_EMERGENCY_ROOM_RECORDS,297.0,NaN,NaN,NaN,0.208754,1.932175,0.0,0.0,0.0,0.0,33.0
ENCOUNTER_URGENT_CARE_RECORDS,297.0,NaN,NaN,NaN,0.225589,1.643872,0.0,0.0,0.0,0.0,19.0
ENCOUNTER_WELL_CHILD_RECORDS,297.0,NaN,NaN,NaN,0.30303,0.732285,0.0,0.0,0.0,0.0,6.0
ENCOUNTER_PRENATAL_RECORDS,297.0,NaN,NaN,NaN,0.511785,1.847395,0.0,0.0,0.0,0.0,11.0
ENCOUNTER_POSTNATAL_RECORDS,297.0,NaN,NaN,NaN,0.047138,0.212292,0.0,0.0,0.0,0.0,1.0
ENCOUNTER_FOLLOW_UP_RECORDS,297.0,NaN,NaN,NaN,0.215488,0.697991,0.0,0.0,0.0,0.0,6.0
ENCOUNTER_INPATIENT_RECORDS,297.0,NaN,NaN,NaN,0.117845,0.438345,0.0,0.0,0.0,0.0,4.0
ENCOUNTER_OTHER_RECORDS,297.0,NaN,NaN,NaN,0.612795,2.147021,0.0,0.0,0.0,1.0,19.0
MEDICATION_START_RECORDS,297.0,NaN,NaN,NaN,4.333333,18.111703,0.0,0.0,1.0,3.0,179.0
PROCEDURE_RECORDS,297.0,NaN,NaN,NaN,16.710438,26.923634,0.0,4.0,9.0,17.0,187.0
DENTAL_PROCEDURE_RECORDS,297.0,NaN,NaN,NaN,4.464646,7.484642,0.0,0.0,0.0,8.0,58.0
SCREENING_ASSESSMENT_RECORDS,297.0,NaN,NaN,NaN,5.521886,11.491493,0.0,0.0,4.0,6.0,107.0
HEIGHT_CM_LAST_IN_YEAR,242.0,NaN,NaN,NaN,158.026446,24.321381,60.7,154.6,164.8,172.5,188.5
HEIGHT_CM_DATE,242,213,05/04/2023,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
WEIGHT_KG_LAST_IN_YEAR,242.0,NaN,NaN,NaN,67.40124,25.984466,5.8,52.55,75.55,83.7,130.4
WEIGHT_KG_DATE,242,213,05/04/2023,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PAIN_SCORE_LAST_IN_YEAR,243.0,NaN,NaN,NaN,2.08642,1.297144,0.0,1.0,2.0,3.0,8.0
PAIN_SCORE_DATE,243,214,05/04/2023,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TOTAL_CHOLESTEROL_LAST_RECORDED,169.0,NaN,NaN,NaN,188.523883,42.383766,120.53,162.15,179.97,213.24,289.94
TOTAL_CHOLESTEROL_DATE,169,97,05/04/2023,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
HDL_CHOLESTEROL_LAST_RECORDED,169.0,NaN,NaN,NaN,49.683035,11.143233,20.8,46.284996,51.67,57.44,79.641656
HDL_CHOLESTEROL_DATE,169,97,05/04/2023,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TRIGLYCERIDES_LAST_RECORDED,169.0,NaN,NaN,NaN,129.165726,22.484602,100.53,112.95,128.21,141.56,273.153097
TRIGLYCERIDES_DATE,169,97,05/04/2023,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
GLUCOSE_LAST_RECORDED,121.0,NaN,NaN,NaN,82.243967,12.474756,64.21,73.15,79.75,90.9,124.49
GLUCOSE_DATE,121,101,31/08/2018,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CREATININE_LAST_RECORDED,121.0,NaN,NaN,NaN,1.742727,1.106084,0.59,0.98,1.28,2.565476,7.42
CREATININE_DATE,121,101,31/08/2018,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
OBESITY_HISTORY,297.0,NaN,NaN,NaN,0.397306,0.490166,0.0,0.0,0.0,1.0,1.0
PREDIABETES_HISTORY,297.0,NaN,NaN,NaN,0.340067,0.474531,0.0,0.0,0.0,1.0,1.0
HYPERTENSION_HISTORY,297.0,NaN,NaN,NaN,0.161616,0.36872,0.0,0.0,0.0,0.0,1.0
ISCHEMIC_HEART_DISEASE_HISTORY,297.0,NaN,NaN,NaN,0.131313,0.338313,0.0,0.0,0.0,0.0,1.0
HYPERLIPIDEMIA_HISTORY,297.0,NaN,NaN,NaN,0.080808,0.273,0.0,0.0,0.0,0.0,1.0
CHRONIC_PAIN_HISTORY,297.0,NaN,NaN,NaN,0.245791,0.431282,0.0,0.0,0.0,0.0,1.0
ASTHMA_HISTORY,297.0,NaN,NaN,NaN,0.070707,0.256768,0.0,0.0,0.0,0.0,1.0
CHRONIC_KIDNEY_DISEASE_HISTORY,297.0,NaN,NaN,NaN,0.043771,0.204931,0.0,0.0,0.0,0.0,1.0
STRESS_HISTORY,297.0,NaN,NaN,NaN,0.747475,0.435194,0.0,0.0,1.0,1.0,1.0
SOCIAL_ISOLATION_HISTORY,297.0,NaN,NaN,NaN,0.653199,0.476755,0.0,0.0,1.0,1.0,1.0
UNEMPLOYMENT_HISTORY,297.0,NaN,NaN,NaN,0.252525,0.435194,0.0,0.0,0.0,1.0,1.0
HOUSING_UNSATISFACTORY_HISTORY,297.0,NaN,NaN,NaN,0.104377,0.306265,0.0,0.0,0.0,0.0,1.0

['BIRTH_DATE', 'PERIOD_START', 'PERIOD_END', 'RECORD_CUTOFF_DATE', 'HEIGHT_CM_DATE', 'WEIGHT_KG_DATE', 'PAIN_SCORE_DATE', 'TOTAL_CHOLESTEROL_DATE', 'HDL_CHOLESTEROL_DATE', 'TRIGLYCERIDES_DATE', 'GLUCOSE_DATE', 'CREATININE_DATE']

   BIRTH_DATE PERIOD_START  PERIOD_END
0  20/01/1981   01/01/2023  31/12/2023
1  20/01/1981   01/01/2024  31/12/2024
2  20/01/1981   01/01/2025  31/12/2025
3  01/11/1972   01/01/2023  31/12/2023
4  01/11/1972   01/01/2024  31/12/2024

{'BIRTH_DATE': 0, 'PERIOD_START': 0, 'PERIOD_END': 0, 'RECORD_CUTOFF_DATE': 0, 'HEIGHT_CM_DATE': 0, 'WEIGHT_KG_DATE': 0, 'PAIN_SCORE_DATE': 0, 'TOTAL_CHOLESTEROL_DATE': 0, 'HDL_CHOLESTEROL_DATE': 0, 'TRIGLYCERIDES_DATE': 0, 'GLUCOSE_DATE': 0, 'CREATININE_DATE': 0}

  BIRTH_DATE PERIOD_START PERIOD_END
0 1981-01-20   2023-01-01 2023-12-31
1 1981-01-20   2024-01-01 2024-12-31
2 1981-01-20   2025-01-01 2025-12-31
3 1972-11-01   2023-01-01 2023-12-31
4 1972-11-01   2024-01-01 2024-12-31